### ISSUE TITLE
Rails 4.0 - Remove assets group in Gemfile

### ISSUE THREAD

**Issue by lucaspiller** [jwo/rails-upgrade_checklist#6]
When upgrading to Rails 4.0, you need to remove the `assets` group in the Gemfile (if any), as [support for that was dropped](https://github.com/rails/rails/commit/49c4af43ec5819d8f5c1a91f9b84296c927ce6e7).

If not your tests may run fine, but when when trying to run the app in development you will get obscure errors like 'Sprockets::FileNotFound'.

**Comment by jwo** [comment]
Thanks @lucaspiller ! This is fixed and deployed with [0c50db](https://github.com/jwo/rails-upgrade_checklist/commit/0c50db0b8578f61380e5fc36d326beb30569d9a5)
